name: Docker

on:
  # Run CI for this branch and all PRs
  push:
    branches:
      - '*-gh-actions'
  pull_request:

jobs:
  build-u500:
    name: Build the U500 firmware image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/checkout@v2
        with:
          repository: riscv/riscv-edk2
          # TODO: Branch specific until riscv-virt is its own platform
          ref: ${{ contains(github.ref, 'riscv-virt') && 'riscv-virt-540-mod' || 'master' }}
          submodules: true
          path: edk2

      - name: Pull image
        run: docker pull ghcr.io/johnazoidberg/riscv-edk2:latest

      - name: Make build directory to access build results
        run: mkdir Build

      - name: Build U500
        run: |
          docker run --rm \
            -v $(pwd)/Build:/Build \
            -v $(pwd)/:/edk2-platforms \
            -v $(pwd)/edk2:/edk2 \
            -i ghcr.io/johnazoidberg/riscv-edk2:latest \
            /edk2-platforms/build-edk2.sh \
            Platform/SiFive/U5SeriesPkg/FreedomU500VC707Board/U500.dsc

      - name: Check if FD files are there
        run: ls -l Build/FreedomU500VC707/DEBUG_GCC5/FV/U500.fd

  build-u540:
    name: Build the U540 firmware image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/checkout@v2
        with:
          repository: riscv/riscv-edk2
          # TODO: Branch specific until riscv-virt is its own platform
          ref: ${{ contains(github.ref, 'riscv-virt') && 'riscv-virt-540-mod' || 'master' }}
          submodules: true
          path: edk2

      - name: Pull image
        run: docker pull ghcr.io/johnazoidberg/riscv-edk2:latest

      - name: Make build directory to access build results
        run: mkdir Build

      - name: Build U540
        run: |
          docker run --rm \
            -v $(pwd)/Build:/Build \
            -v $(pwd)/:/edk2-platforms \
            -v $(pwd)/edk2:/edk2 \
            -i ghcr.io/johnazoidberg/riscv-edk2:latest \
            /edk2-platforms/build-edk2.sh \
            Platform/SiFive/U5SeriesPkg/FreedomU540HiFiveUnleashedBoard/U540.dsc

      - name: Check if FD files are there
        run: ls -l Build/FreedomU540HiFiveUnleashed/DEBUG_GCC5/FV/U540.fd

      - uses: actions/upload-artifact@master
        with:
          name: U540
          path: Build/FreedomU540HiFiveUnleashed/DEBUG_GCC5/FV

  build-virt:
    name: Build the QEMU RiscvVirt firmware image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/checkout@v2
        with:
          repository: riscv/riscv-edk2
          # TODO: Branch specific until riscv-virt is its own platform
          ref: ${{ contains(github.ref, 'riscv-virt') && 'riscv-virt-540-mod' || 'master' }}
          submodules: true
          path: edk2

      - name: Pull image
        run: docker pull ghcr.io/johnazoidberg/riscv-edk2:latest

      - name: Make build directory to access build results
        run: mkdir Build

      - name: Build RiscvVirt
        run: |
          docker run --rm \
            -v $(pwd)/Build:/Build \
            -v $(pwd)/:/edk2-platforms \
            -v $(pwd)/edk2:/edk2 \
            -i ghcr.io/johnazoidberg/riscv-edk2:latest \
            /edk2-platforms/build-edk2.sh \
            Platform/Qemu/RiscvVirt/RiscvVirt.dsc

      - name: Check if FD files are there
        run: ls -l Build/RiscvVirt/DEBUG_GCC5/FV/RISCVVIRT.fd

      - uses: actions/upload-artifact@master
        with:
          name: RiscvVirt
          path: Build/RiscvVirt/DEBUG_GCC5/FV

  test-u540:
    name: Boot the image to UEFI Shell
    if: ${{ contains(github.ref, 'riscv-virt') }}
    runs-on: ubuntu-latest
    needs: build-u540
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: U540
          path: Build/FreedomU540HiFiveUnleashed/DEBUG_GCC5/FV

      - name: Chmod U540.fd
        run: chmod +w Build/FreedomU540HiFiveUnleashed/DEBUG_GCC5/FV/U540.fd

      # Call the custom action in this repo at /action.yml
      - uses: ./
        with:
          entrypoint: './run-u540.sh'

  test-virt:
    name: Boot the image to UEFI Shell
    if: ${{ contains(github.ref, 'riscv-virt') }}
    runs-on: ubuntu-latest
    needs: build-virt
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: RiscvVirt
          path: Build/RiscvVirt/DEBUG_GCC5/FV

      - name: Chmod RISCVVIRT.fd
        run: chmod +w Build/RiscvVirt/DEBUG_GCC5/FV/RISCVVIRT.fd

      # Call the custom action in this repo at /action.yml
      - uses: ./
        with:
          entrypoint: './run-virt.sh'
